version: "3.9"
services:
  backend:
    container_name: django
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/app
    networks:
      - trandung
networks:
  trandung:
